# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - testing-3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: â¬ Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: ğŸ“¦ Install dependencies, build, test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./server

      - name: ğŸ“¦ Zip project
        run: zip -r release.zip .
        working-directory: ./server

      - name: â˜ï¸ Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: â¬ Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: ğŸ“‚ Unzip backend
        run: unzip release.zip

      - name: ğŸ” Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BE56F3E66CC1460B8164FF0D91A02DE8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C704AF9C97CC4FC8A0F569C18C027C7D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6CB3FD5E6DB945ECA7585668C71AAC4C }}

      - name: ğŸš€ Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testing-web'
          slot-name: 'Production'
          package: .
